export const movie_list = 
[{
	id: 0,
	votes:0,
	movie:'Dear Zindagi ',
	year:'2016 .',
	time:'2h 31m',
	genres: 'Drama Romance',
	description:'kaira is a building cinemagrapher in search of a perfect life. her encounter with jug, an unconventional thinker.helps her gain a new perspective on life .she discovers that happiness ia all about finding comfort in life"s imperfections',
	url:'image1.png',
},	
{
	id: 1,
    votes:0,
	movie:'Brave',
	year:'2012 .',
	time:'1h 33h',
	genres: 'Adventures, comedy',
	description:'Determind to make her own path in life, princess merida defins a custom that brings chaos to her kingdom granted one wish , marida must rely on her bravery and her archery skills to undo a beastly curse.',
	url:'image2.png',
}, 
{
	id: 2,
    votes:0,
	movie: 'Moana',
	year:'2016 . ',
	time:'1h 47m',
	genres: 'Adventures, comedy',
	description:'In ancient polynesia when a teritible curse incurred by the demingold maui reaches maona"s island .she answers the ocean call to seek out the demingold to set the things right',
    url:'image3.png',
	}, 
	
{
	id: 3,
	votes:0,
	movie: 'Mulan',
	year: '1998 .',
	time: '1h 27m',
	genres: 'Adventures, comedy',
	description:"To save her father from death in the army, a young maiden secretly goes in his place and becomes one of China's greatest heroines in the process.",
	url:'image4.png',
	}, 	
	
{
	id: 4,
	votes:0,
	movie: 'He Named Me Malala',
	year: '2015 .',
	time: '1h 28m ',
	genres: 'Biography, Documentary',
	description:"A look at the events leading up to the Taliban's attack on Pakistani schoolgirl Malala Yousafzai for speaking out on girls' education, followed by the aftermath, including her speech to the United Nations.",
	url:'image5.png',
	}, 
	
{
	id: 5,
	votes:0,
	movie: 'Soul surfer',
	year: '2011 .',
	time: '1h 52m',
	genres: 'Drama, Biography, Family',
	description:"Teenage surfer Bethany Hamilton overcomes the odds and her own fears of returning to the water after losing her left arm in a shark attacks",
	url:'image6.png',
	}, 
	
{
	id: 6,
	votes:0,
	movie: 'Bend It Like Beckham',
	year: '2002 .',
	time: '1h 52m',
	genres: 'comedy, drama & Romance',
	description:"Two ambitious girls, despite their parents' wishes, have their hearts set on careers in professional football.",
	url:'image7.png',
	}, 
	
{
	id: 7,
	votes:0,
	movie: 'Into The Wild',
	year: '2007 .',
	time: '2h 28m',
	genres: 'Adventures, Biograpgy, Drama',
	description:"After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity and hitchhikes to Alaska to live in the wilderness. Along the way, Christopher encounters a series of characters that shape his life.",
	url:'image10.png',
	}, 
	
	
{
	id: 8,
	votes:0,
	movie: 'The Pursuit Of Happyness',
	year: '2006 .',
	time: '1h 57m',
	genres: 'Drama, Biograpgy',
	description:"A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career.",
	url:'image9.png',
	}, 
	
{
	id: 9,
	votes:0,
	movie: 'The Intouchables',
	year: '2011 .',
	time: '1h 52m ',
	genres: 'Drama, Biograpgy',
	description:"After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver",
	url:'image8.png',
	}, 
]